language: php

php:
- 7.1
- 7.2
- hhvm

before_script:
- composer self-update
- composer install --prefer-source --no-interaction --dev

cache:
  directories:
  - $HOME/.composer/cache
  - $HOME/.php-cs-fixer

script:
  - php -dzend_extension=xdebug.so ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/php-cs-fixer fix -v --diff --dry-run

notifications:
  on_success: never
  on_failure: always