language: php

php:
- 7.1
- 7.2

before_script:
- composer self-update
- composer install --prefer-source --no-interaction --dev

cache:
  directories:
  - $HOME/.composer/cache
  - $HOME/.php-cs-fixer

script:
  - ./vendor/bin/phpunit -c phpunit.xml.dist
  - ./vendor/bin/php-cs-fixer fix

notifications:
  on_success: never
  on_failure: always

after_success:
  - travis_retry php vendor/bin/php-coveralls