<?php

return [
    [
        'Name' => 'ALBANIAN EQUESTRIAN SPORTS FEDERATION',
        'CountryCode' => 'ALB',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'AMERICAN SAMOA EQUESTRIAN FEDERATION',
        'CountryCode' => 'ASA',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'ANTIGUA & BARBUDA HORSE SOCIETY ',
        'CountryCode' => 'ANT',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'ASOCIACIÓN NACIONAL DE ECUESTRES DE GUATEMALA',
        'CountryCode' => 'GUA',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'ASSOCIATION OF EQUESTRIAN ORGANISATIONS OF BOSNIA AND HERZEGOVINA',
        'CountryCode' => 'BIH',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'BAHAMAS NATIONAL EQUESTRIAN FEDERATION',
        'CountryCode' => 'BAH',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'BAHRAIN ROYAL EQUESTRIAN & ENDURANCE FEDERATION',
        'CountryCode' => 'BRN',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'BARBADOS EQUESTRIAN ASSOCIATION ',
        'CountryCode' => 'BAR',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'BERMUDA EQUESTRIAN FEDERATION ',
        'CountryCode' => 'BER',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'BRITISH EQUESTRIAN FEDERATION ',
        'CountryCode' => 'GBR',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'BRUNEI EQUINE ASSOCIATION',
        'CountryCode' => 'BRU',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'BULGARIAN EQUESTRIAN FEDERATION ',
        'CountryCode' => 'BUL',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'CAMBODIAN EQUESTRIAN FEDERATION',
        'CountryCode' => 'CAM',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'CAYMAN ISLANDS EQUESTRIAN FEDERATION',
        'CountryCode' => 'CAY',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'CHINESE EQUESTRIAN ASSOCIATION',
        'CountryCode' => 'CHN',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'CHINESE TAIPEI EQUESTRIAN ASSOCIATION',
        'CountryCode' => 'TPE',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'CONFEDERAÇÃO BRASILEIRA DE HIPISMO',
        'CountryCode' => 'BRA',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'CROATIAN EQUESTRIAN FEDERATION ',
        'CountryCode' => 'CRO',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'CYPRUS EQUESTRIAN FEDERATION ',
        'CountryCode' => 'CYP',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'CZECH EQUESTRIAN FEDERATION ',
        'CountryCode' => 'CZE',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'DANSK RIDE FORBUND',
        'CountryCode' => 'DEN',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'DEUTSCHE REITERLICHE VEREINIGUNG ',
        'CountryCode' => 'GER',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'EGYPTIAN EQUESTRIAN FEDERATION (EEF)',
        'CountryCode' => 'EGY',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'EMIRATES EQUESTRIAN FEDERATION',
        'CountryCode' => 'UAE',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'EQUESTRIAN  AUSTRALIA  ',
        'CountryCode' => 'AUS',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'EQUESTRIAN  FEDERATION OF UZBEKISTAN',
        'CountryCode' => 'UZB',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'EQUESTRIAN ASSOCIATION OF MALAYSIA',
        'CountryCode' => 'MAS',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'EQUESTRIAN ASSOCIATION OF THE PHILIPPINES',
        'CountryCode' => 'PHI',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'EQUESTRIAN CANADA EQUESTRE',
        'CountryCode' => 'CAN',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'EQUESTRIAN FEDERATION OF ARMENIA',
        'CountryCode' => 'ARM',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'EQUESTRIAN FEDERATION OF AZERBAIJAN',
        'CountryCode' => 'AZE',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'EQUESTRIAN FEDERATION OF BELARUS',
        'CountryCode' => 'BLR',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'EQUESTRIAN FEDERATION OF ESTONIA ',
        'CountryCode' => 'EST',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'EQUESTRIAN FEDERATION OF INDIA ',
        'CountryCode' => 'IND',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'EQUESTRIAN FEDERATION OF IRAQ',
        'CountryCode' => 'IRQ',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'EQUESTRIAN FEDERATION OF JAMAICA',
        'CountryCode' => 'JAM',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'EQUESTRIAN FEDERATION OF PAKISTAN',
        'CountryCode' => 'PAK',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'EQUESTRIAN FEDERATION OF SINGAPORE',
        'CountryCode' => 'SGP',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'EQUESTRIAN FEDERATION OF SLOVENIA',
        'CountryCode' => 'SLO',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'EQUESTRIAN FEDERATION OF THE ISLAMIC REPUBLIC OF IRAN',
        'CountryCode' => 'IRI',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'EQUESTRIAN SPORTS NEW ZEALAND',
        'CountryCode' => 'NZL',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'ETHIOPIAN EQUESTRIAN ASSOCIATION',
        'CountryCode' => 'ETH',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERAÇÃO EQUESTRE DE ANGOLA',
        'CountryCode' => 'ANG',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERAÇÃO EQUESTRE PORTUGUESA ',
        'CountryCode' => 'POR',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'FEDERACIÓ ANDORRANA D\'HÍPICA',
        'CountryCode' => 'AND',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERACIÓN  ECUESTRE DE CHILE ',
        'CountryCode' => 'CHI',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERACIÓN BOLIVIANA DE DEPORTES ECUESTRES',
        'CountryCode' => 'BOL',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERACIÓN DE DEPORTES ECUESTRES DEL PARAGUAY    (FEDEPA)',
        'CountryCode' => 'PAR',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERACIÓN DOMINICANA DE DEPORTES ECUESTRES INC.',
        'CountryCode' => 'DOM',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'FEDERACIÓN ECUATORIANA DE DEPORTES ECUESTRES',
        'CountryCode' => 'ECU',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERACIÓN ECUESTRE ARGENTINA ',
        'CountryCode' => 'ARG',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'FEDERACIÓN ECUESTRE CUBANA ',
        'CountryCode' => 'CUB',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERACIÓN ECUESTRE DE COLOMBIA',
        'CountryCode' => 'COL',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERACIÓN ECUESTRE DE COSTA RICA',
        'CountryCode' => 'CRC',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERACIÓN ECUESTRE DE HONDURAS',
        'CountryCode' => 'HON',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERACION ECUESTRE DE NICARAGUA',
        'CountryCode' => 'NCA',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERACION ECUESTRE MEXICANA ',
        'CountryCode' => 'MEX',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'FEDERACIÓN PERUANA DE DEPORTES ECUESTRES',
        'CountryCode' => 'PER',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERACIÓN PUERTORRIQUEÑA DE DEPORTES ECUESTRES',
        'CountryCode' => 'PUR',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERACIÓN SALVADOREÑA  DE ECUESTRES',
        'CountryCode' => 'ESA',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'FEDERACIÓN URUGUAYA DE DEPORTES ECUESTRES',
        'CountryCode' => 'URU',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERACIÓN VENEZOLANA DE DEPORTES ECUESTRES',
        'CountryCode' => 'VEN',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERATIA ECVESTRA A REPUBLICII MOLDOVA',
        'CountryCode' => 'MDA',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERATION ARABE SYRIENNE DES SPORTS EQUESTRES',
        'CountryCode' => 'SYR',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'FEDERATION CAMEROUNAISE DES SPORTS EQUESTRES',
        'CountryCode' => 'CMR',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERATION CONGOLAISE DES SPORTS EQUESTRES (F.C.S.E.)',
        'CountryCode' => 'COD',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERATION DES SPORTS EQUESTRES DE MADAGASCAR ',
        'CountryCode' => 'MAD',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERATION EQUESTRE ALGERIENNE',
        'CountryCode' => 'ALG',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERATION EQUESTRE DE LA PRINCIPAUTE DE MONACO',
        'CountryCode' => 'MON',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERATION EQUESTRE HAITIENNE ',
        'CountryCode' => 'HAI',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERATION EQUESTRE LIBANAISE  ',
        'CountryCode' => 'LBN',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERATION EQUESTRE POLONAISE ',
        'CountryCode' => 'POL',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERATION EQUESTRE ROUMAINE ',
        'CountryCode' => 'ROU',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERATION FOR EQUESTRIAN SPORT OF SERBIA FOR OLYMPIC AND FEI DISCIPLINES OF EQUESTRIAN SPORT',
        'CountryCode' => 'SRB',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERATION FRANÇAISE D\'EQUITATION',
        'CountryCode' => 'FRA',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'FEDERATION LUXEMBOURGEOISE DES SPORTS EQUESTRES',
        'CountryCode' => 'LUX',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'FEDERATION OF EQUESTRIAN SPORTS OF RUSSIA',
        'CountryCode' => 'RUS',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'FEDERATION ROYALE BELGE DES SPORTS EQUESTRES',
        'CountryCode' => 'BEL',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'FEDERATION ROYALE MAROCAINE DES SPORTS EQUESTRES',
        'CountryCode' => 'MAR',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERATION SENEGALAISE DES SPORTS EQUESTRES',
        'CountryCode' => 'SEN',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEDERATION SUISSE DES SPORTS EQUESTRES',
        'CountryCode' => 'SUI',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'FEDERATION TUNISIENNE DES SPORTS  EQUESTRES',
        'CountryCode' => 'TUN',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'FEDERAZIONE IPPICA SAMMARINESE ',
        'CountryCode' => 'SMR',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'FEI Flag',
        'CountryCode' => '',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'GRENADA INTERNATIONAL SPORTS FOUNDATION',
        'CountryCode' => 'GRN',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'HELLENIC EQUESTRIAN FEDERATION ',
        'CountryCode' => 'GRE',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'HONG KONG EQUESTRIAN FEDERATION',
        'CountryCode' => 'HKG',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'HORSE ASSOCIATION OF KENYA ',
        'CountryCode' => 'KEN',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'HORSE SPORT IRELAND',
        'CountryCode' => 'IRL',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'HUNGARIAN EQUESTRIAN FEDERATION ',
        'CountryCode' => 'HUN',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'ISRAEL EQUESTRIAN FEDERATION ',
        'CountryCode' => 'ISR',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'ITALIAN EQUESTRIAN FEDERATION ',
        'CountryCode' => 'ITA',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'JAPAN EQUESTRIAN FEDERATION ',
        'CountryCode' => 'JPN',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'KAZAKHSTAN EQUESTRIAN FEDERATION',
        'CountryCode' => 'KAZ',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'KOREA EQUESTRIAN FEDERATION ',
        'CountryCode' => 'KOR',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'KUWAIT EQUESTRIAN FEDERATION ',
        'CountryCode' => 'KUW',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'LATVIAN EQUESTRIAN FEDERATION ',
        'CountryCode' => 'LAT',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'LESOTHO EQUESTRIAN FEDERATION',
        'CountryCode' => 'LES',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'LIBYAN ARAB EQUESTRIAN FEDERATION',
        'CountryCode' => 'LBA',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'LIECHTENSTEINER PFERDESPORT- VERBAND',
        'CountryCode' => 'LIE',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'LITHUANIAN EQUESTRIAN ASSOCIATION',
        'CountryCode' => 'LTU',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'MALAWI EQUESTRIAN FEDERATION',
        'CountryCode' => 'MAW',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'MAURITIAN EQUESTRIAN SPORTS FEDERATION',
        'CountryCode' => 'MRI',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'MONGOLIAN EQUESTRIAN FEDERATION',
        'CountryCode' => 'MGL',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'MYANMAR EQUESTRIAN FEDERATION ',
        'CountryCode' => 'MYA',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'NAMIBIAN EQUESTRIAN FEDERATION',
        'CountryCode' => 'NAM',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'NATIONAL EQUESTRIAN FEDERATION OF FYROMACEDONIA',
        'CountryCode' => 'MKD',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'NATIONAL EQUESTRIAN FEDERATION OF GEORGIA',
        'CountryCode' => 'GEO',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'NATIONAL EQUESTRIAN FEDERATION OF MALTA',
        'CountryCode' => 'MLT',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'NORGES RYTTERFORBUND NORWEGIAN EQUESTRIAN FEDERATION',
        'CountryCode' => 'NOR',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'ÖESTERREICHISCHER PFERDESPORTVERBAND',
        'CountryCode' => 'AUT',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'OMAN EQUESTRIAN FEDERATION ',
        'CountryCode' => 'OMA',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'ORGANIZACIÓN ECUESTRE DE PANAMÁ',
        'CountryCode' => 'PAN',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'PALESTINE EQUESTRIAN FEDERATION',
        'CountryCode' => 'PLE',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'PP. PORDASI - THE INDONESIAN SPORTHORSE SOCIETY',
        'CountryCode' => 'INA',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'QATAR EQUESTRIAN FEDERATION ',
        'CountryCode' => 'QAT',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'REAL FEDERACIÓN HÍPICA ESPAÑOLA',
        'CountryCode' => 'ESP',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'ROYAL DUTCH EQUESTRIAN FEDERATION',
        'CountryCode' => 'NED',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'ROYAL JORDANIAN EQUESTRIAN FEDERATION',
        'CountryCode' => 'JOR',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'SAUDI ARABIAN EQUESTRIAN FEDERATION',
        'CountryCode' => 'KSA',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'SLOVAK EQUESTRIAN FEDERATION ',
        'CountryCode' => 'SVK',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'SOUTH AFRICAN  EQUESTRIAN FEDERATION',
        'CountryCode' => 'RSA',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'SRI LANKA EQUESTRIAN ASSOCIATION',
        'CountryCode' => 'SRI',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'STICHTING ANTILLIAANSE HIPPISCHE SPORTBOND',
        'CountryCode' => 'AHO',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'SUDAN EQUESTRIAN FEDERATION ',
        'CountryCode' => 'SUD',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'SVENSKA RIDSPORTFÖRBUNDET ',
        'CountryCode' => 'SWE',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'SWAZILAND EQUESTRIAN FEDERATION',
        'CountryCode' => 'SWZ',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'THAILAND EQUESTRIAN FEDERATION  (TEF)',
        'CountryCode' => 'THA',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'THE EQUESTRIAN ASSOCIATION OF ICELAND',
        'CountryCode' => 'ISL',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'THE EQUESTRIAN FEDERATION OF FINLAND',
        'CountryCode' => 'FIN',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'THE EQUESTRIAN FEDERATION OF THE KYRGYZSTAN REPUBLIC',
        'CountryCode' => 'KGZ',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'THE EQUESTRIAN FEDERATION OF UKRAINE',
        'CountryCode' => 'UKR',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'THE HORSE SOCIETY OF BOTSWANA ',
        'CountryCode' => 'BOT',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'THE SURINAMESE EQUESTRIAN SPORTS ORGANIZATION',
        'CountryCode' => 'SUR',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'THE TRINIDAD AND TOBAGO EQUESTRIAN ASSOCIATION',
        'CountryCode' => 'TRI',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'To be determined',
        'CountryCode' => '',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'TURKISH EQUESTRIAN FEDERATION ',
        'CountryCode' => 'TUR',
        'IsHorseAdminChangeAutoAccepted' => true,
        'IsRiderAdminChangeAutoAccepted' => true,
    ],
    [
        'Name' => 'TURKMEN EQUESTRIAN FEDERATION ',
        'CountryCode' => 'TKM',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'US EQUESTRIAN',
        'CountryCode' => 'USA',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'VIRGIN ISLANDS EQUESTRIAN ASSOCIATION',
        'CountryCode' => 'ISV',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'YEMEN EQUESTRIAN FEDERATION',
        'CountryCode' => 'YEM',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'ZAMBIA NATIONAL EQUESTRIAN FEDERATION',
        'CountryCode' => 'ZAM',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
    [
        'Name' => 'ZIMBABWE EQUESTRIAN FEDERATION',
        'CountryCode' => 'ZIM',
        'IsHorseAdminChangeAutoAccepted' => false,
        'IsRiderAdminChangeAutoAccepted' => false,
    ],
];
