<?php

namespace FEIWebServicesClient\Shared\Types;

use Assert\Assert;

class NationalFederation
{
    private $country;

    public function __construct(Country $country)
    {
        Assert::that($country->FEIcode())->inArray($this->nationalFederationList());
        $this->country = $country;
    }

    public function country(): Country
    {
        return $this->country;
    }

    public function __toString(): string
    {
        return $this->country->FEIcode();
    }


    private function nationalFederationList(): array
    {
        return [
            'ALB',
            'ASA',
            'ANT',
            'GUA',
            'BIH',
            'BAH',
            'BRN',
            'BAR',
            'BER',
            'GBR',
            'BRU',
            'BUL',
            'CAM',
            'CAY',
            'CHN',
            'TPE',
            'BRA',
            'CRO',
            'CYP',
            'CZE',
            'DEN',
            'GER',
            'EGY',
            'AUS',
            'UZB',
            'MAS',
            'PHI',
            'CAN',
            'ARM',
            'AZE',
            'BLR',
            'EST',
            'IND',
            'IRQ',
            'JAM',
            'PAK',
            'SGP',
            'SLO',
            'IRI',
            'NZL',
            'ETH',
            'ANG',
            'POR',
            'AND',
            'CHI',
            'BOL',
            'PAR',
            'DOM',
            'ECU',
            'ARG',
            'CUB',
            'COL',
            'CRC',
            'HON',
            'NCA',
            'MEX',
            'PER',
            'PUR',
            'ESA',
            'URU',
            'VEN',
            'MDA',
            'SYR',
            'CMR',
            'COD',
            'MAD',
            'ALG',
            'MON',
            'HAI',
            'LBN',
            'POL',
            'ROU',
            'SRB',
            'FRA',
            'LUX',
            'RUS',
            'BEL',
            'MAR',
            'SEN',
            'SUI',
            'TUN',
            'SMR',
            'GRN',
            'GRE',
            'HKG',
            'KEN',
            'IRL',
            'HUN',
            'ISR',
            'ITA',
            'JPN',
            'KAZ',
            'KOR',
            'KUW',
            'LAT',
            'LES',
            'LBA',
            'LIE',
            'LTU',
            'MAW',
            'MRI',
            'MGL',
            'MYA',
            'NAM',
            'MKD',
            'GEO',
            'MLT',
            'NOR',
            'AUT',
            'OMA',
            'PAN',
            'PLE',
            'INA',
            'QAT',
            'ESP',
            'NED',
            'JOR',
            'KSA',
            'SVK',
            'RSA',
            'SRI',
            'AHO',
            'SUD',
            'SWE',
            'SWZ',
            'THA',
            'ISL',
            'FIN',
            'KGZ',
            'UKR',
            'BOT',
            'SUR',
            'TRI',
            'TUR',
            'TKM',
            'UAE',
            'USA',
            'ISV',
            'YEM',
            'ZAM',
            'ZIM',
        ];
    }
}
